name: education_center
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  l: ^5.0.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  lottie: ^3.1.3
  firebase_core: ^3.8.1
  http_interceptor: ^2.0.0
  http: ^1.2.2
  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
