// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQck9_dLlIWhdjUEoIbxcDDRgI8iI7z40',
    appId: '1:106387897361:web:c1c4b6ac7e2c33f96d85b0',
    messagingSenderId: '106387897361',
    projectId: 'educationcenter-bfe72',
    authDomain: 'educationcenter-bfe72.firebaseapp.com',
    databaseURL: 'https://educationcenter-bfe72-default-rtdb.firebaseio.com',
    storageBucket: 'educationcenter-bfe72.firebasestorage.app',
    measurementId: 'G-TTF54QG5K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDoLbG9ZiX-Gxlls6wMa12S27Hu4-v2o',
    appId: '1:106387897361:android:6fe0ca88b88059346d85b0',
    messagingSenderId: '106387897361',
    projectId: 'educationcenter-bfe72',
    databaseURL: 'https://educationcenter-bfe72-default-rtdb.firebaseio.com',
    storageBucket: 'educationcenter-bfe72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKSrKGJcb3DubtzeRsXaeocnjE3ZjplnA',
    appId: '1:106387897361:ios:cef7dd4bcb7c28116d85b0',
    messagingSenderId: '106387897361',
    projectId: 'educationcenter-bfe72',
    databaseURL: 'https://educationcenter-bfe72-default-rtdb.firebaseio.com',
    storageBucket: 'educationcenter-bfe72.firebasestorage.app',
    iosBundleId: 'com.example.educationCenter',
  );
}
